dist: bionic

perl:
  - '5.34'
  - '5.32'
  - '5.30'
  - '5.28'

before_install:
  # These are needed to test debian package build
  - sudo apt-get install debhelper fakeroot cpanminus
  # Install packages needed for testing
  - sudo cpanm Test::Cmd Test::Exception File::Which

script:
  - ./configure.bash
  - make test
  - sudo mv /dev/stdout /dev/stdout.bak
  - make test
  - make dist
  - make distcheck
  - make disttest
  # Test debian package building
  - dpkg-buildpackage -b -us -uc
