name: test

on:
  push:
    branches:
    - master
    - 'release-*'
  pull_request:
    branches:
    - '*'

jobs:

  test:

    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            perl:
              - "5.30"
              - "5.28"
              - "5.26"
              - "5.24"
              - "5.22"
            os:
              - ubuntu-18.04
    env:
      APT: "apt-get -o Dpkg::Progress=0 -o Dpkg::Use-Pty=0"
    steps:
    - uses: actions/checkout@v1
    - name: Setup perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}
    - name: Install dependencies
      run: |
        # Install dependencies
        sudo -E ${APT} -qq install --no-install-recommends \
            cpanminus \
            debhelper \
            fakeroot \
            libfile-which-perl
        cpanm \
            File::Which \
            Module::Build \
            Test::Cmd \
            Test::Exception
    - name: Build
      run: |
        perl --version
        ./configure
        make
    - name: Test build
      run: |
        make test
        sudo mv /dev/stdout /dev/stdout.bak
        make test
    - name: Test distribution
      run: |
        make dist
        make distcheck
        make disttest
    - name: Test packaging
      run: |
        make deb
        # Installing requires linz-bde-copy which is still
        # unpackaged on packagecloud for bionic, see
        # https://github.com/linz/linz-bde-copy/issues/44
        #sudo dpkg -i ../liblinz-bde-perl*.deb

  package:
    if: ${{ success() }}
    name: Package for Debian
    runs-on: ubuntu-18.04
    strategy:
        matrix:
            distro: [ 'bionic' ]
    steps:
    - uses: actions/checkout@v1

    - name: Determine packagecloud publication target
      run: |
        # TODO: it would be nice to turn this into a single-liner in
        #       github-action syntax
        echo "GitHub ref: ${{ github.ref }}"
        echo "GitHub event_name: ${{ github.event_name }}"
        REPO=
        if test "${{ github.event_name }}" = 'push'; then
          if expr "${{ github.ref }}" : "refs/tags/" > /dev/null; then
            REPO=test
          elif test "${{ github.ref }}" = 'refs/heads/packagecloud' -o
               test "${{ github.ref }}" = 'refs/heads/master'
          then
            REPO=dev
          fi
        fi
        echo "REPO: $REPO"
        echo ::set-env name=REPO::"$REPO"

    - uses: linz/linz-software-repository@master
      with:
        packagecloud_token: ${{ secrets.LINZCI_PACKAGECLOUD_TOKEN }}
        publish_to_repository: ${{ env.REPO }}
